<?php

    $appId = Mage::getStoreConfig( 'ecomail_options/properties/app_id' );
    if( $appId ) {

        $html = <<<HTML
<script type="text/javascript">            
    EcomailFront.init({1});
</script>
HTML;

        $html = strtr(
                $html,
                array(
                        '{1}' => json_encode(
                                array(
                                        'basePath'                   => Mage::app()
                                                                            ->getRequest()
                                                                            ->getBasePath(),
                                        'cookieNameTrackStructEvent' => Mage::helper( 'ecomail' )
                                                                            ->getCookieNameTrackStructEvent()
                                )
                        )
                )
        );

        echo $html;

        $html = <<<HTML
                
<!-- Ecomail starts -->
<script type="text/javascript">
;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
};p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d1fc8wv8zag5ca.cloudfront.net/2.4.2/sp.js","ecotrack"));
window.ecotrack('newTracker', 'cf', 'd2dpiwfhf3tz0r.cloudfront.net', {1});
window.ecotrack('setUserIdFromLocation', 'ecmid');
window.ecotrack('trackPageView');
</script>
<!-- Ecomail stops -->
HTML;

        $html = strtr(
                $html,
                array(
                        '{1}' => json_encode(
                                array(
                                        'appId' => $appId
                                )
                        )
                )
        );

        echo $html;
    }